---
title: Analysis for "Assessment of Menstrual Health Status and Evolution through Mobile Apps for Fertility Awareness""
author: "Laura Symul, Katarzyna Wac, Paula Hillard and Marcel Salathé"
date: "2019"
output: 
  bookdown::html_document2: 
    theme: flatly
    highlight: haddock
    toc: yes
    toc_float: true
    toc_depth: 5
    number_sections: true
    fig_caption: true

---

```{r setup setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```


```{r load libraries functions etc, results = FALSE, warnings = FALSE, eval = TRUE}
source("Scripts/libraries.R")
source("Scripts/variables.R")
source("Scripts/functions.R")
```


This file contains all the code for the analysis of the data for the figures. 
The preprocessing of the original data and the ovulation estimation with the HMM are done in "Scripts/main_analysis_sympto.R" and in "Scripts/main_analysis_kindara.R"

```{r child = '_user_history.Rmd', cache=TRUE}
```


```{r child = '_user_demographics.Rmd', cache=TRUE}
```


```{r child = '_tracking_frequency.Rmd', cache=TRUE}
```


```{r child = '_overall_profiles.Rmd', cache=TRUE}
```


```{r child = '_cycle_phases_duration.Rmd', cache=TRUE}
```


```{r child = '_estimation_quality.Rmd', cache=TRUE}
```


```{r child = '_states_by_cycle_length.Rmd', cache=TRUE}
```


```{r child = '_comparison_of_phases_durations.Rmd', cache=TRUE}
```


```{r child = '_HMM_justification.Rmd', cache=TRUE}
```


```{r child = '_most_useful_signs_for_ovulation.Rmd', cache=TRUE}
```





